create modularity
idiv-biodiversity/ansible-role-nrpe pull request #2
Opened 2020-11-17 10:35 UTC by sloan87

have it in master to check it with ansible

2021-07-05 06:05 UTC, wookietreiber commented
Sorry about the delay @DirectorSloan, doing the review now.

2021-07-05 06:07 UTC, wookietreiber requested changes

2021-07-05 06:07 UTC, wookietreiber commented on tasks/install_suse.yml
> +...
Please add final newline here.

2021-07-05 06:07 UTC, wookietreiber commented on tasks/install_redhat.yml
> +  until: nrpe_installed is succeeded
Please use `__nrpe_installed` for internal variables.

2021-07-05 06:07 UTC, wookietreiber commented on tasks/install_suse.yml
> +  until: nrpe_installed is succeeded
Please use `__nrpe_installed` for internal variables.

2021-07-05 06:11 UTC, wookietreiber requested changes
Since this PR is basically about adding SUSE to the supported distros, please add the OpenSUSE versions you tested with to the `meta/main.yml` platforms list. You can find the versions supported by Ansible Galaxy [here](https://galaxy.ansible.com/api/v1/platforms/?search=suse).

2022-03-02 13:25 UTC, DirectorSloan commented
do much delay, closing pr

2022-03-02 13:25 UTC, closed without merging